language: node_js
node_js:
  - '5'

script:
  - 'npm test'

after_script:
  - 'find ./coverage -name lcov.info -exec cat {} \; | ./node_modules/.bin/coveralls'
  - 'npm run build'
  - 'sha256sum ./dist/chrome/*'
  - 'sha256sum ./dist/firefox/*'
  - 'sha256sum ./dist/opera/*'
